### PR TITLE
perf:  🚀 speed up with simd

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
before: 
image

 after:
截屏2021-08-02 下午3 51 44

**Comment by IWANABETHATGUY** [comment]
need to compile with `target-feature` flag, on my mac, i use 
`RUSTFLAGS="-C target-feature=+avx2" cargo bench`
reference: https://rust-lang.github.io/packed_simd/perf-guide/target-feature/rustflags.html

**Comment by IWANABETHATGUY** [comment]
if i remove 
```
let has_ascii = str.chars().any(|c| c as u32 <= 255);
  if has_ascii {
      return false;
  }
```
get the bench result below 
image
I think this because rust chars call the function `from_utf8`, which has big overhead

**Comment by IWANABETHATGUY** [comment]
found some bug , will reopen after i fix this bug

**Comment by alsotang** [comment]
This optimization can not run on stable rust??

```shell
   Compiling packed_simd_2 v0.3.5
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/atang/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.5/src/lib.rs:214:1
    |
214 | / #![feature(
215 | |     const_generics,
216 | |     repr_simd,
217 | |     rustc_attrs,
...   |
227 | |     llvm_asm
228 | | )]
    | |__^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `packed_simd_2`
```

**Comment by IWANABETHATGUY** [comment]
yes, simd in rust is not stable yet

**Comment by alsotang** [comment]
You can create a `simd` branch in this repo and write it in readme. But I won't merge this into `main` until simd is a stable feature.
Is this ok?

**Comment by IWANABETHATGUY** [comment]
> You can create a `simd` branch in this repo and write it in readme. But I won't merge this into `main` until simd is a stable feature.
> Is this ok?
ok👌

**Comment by alsotang** [comment]
You said there are some bugs in your solution, but the test cases couldn't reflect them. 
Can you help to add test cases?

**Pull request closed without merging**
